# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LivePhotoTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LivePhotoTestApp

pod 'Alamofire'
pod 'Realm'

end
